# Source: seldon-core-operator/templates/clusterrolebinding_seldon-manager-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'seldon-core'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.12.0'
  name: seldon-manager-rolebinding-seldon-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-manager-role-seldon-system
subjects:
- kind: ServiceAccount
  name: 'seldon-manager'
  namespace: 'seldon-system'
